### PR TITLE
Fixes and improvements.

### PR DESCRIPTION
**Pull request by rsxrwscjpzdzwpxaujrr**
Hello, the project is abandoned and currently isn't working, but I needed to scrape some media, so I fixed it and made some improvements. That includes:

- Fix of #7 
- Fix of #9 
- Fix of `vk_api.exceptions.ApiError: [13] Runtime error occurred during code invocation: response size is too big`
- Functionality for scraping from the wall
- Offset argument
- Refactoring (despite the new functionality, the code lines count dropped by 20)

### CODE REVIEW

**Comment by DrLightman** [comment]
Hi, could you help me to install these fixes to a newbie python user like me?
I installed python 3.11 for Windows and installed vk-scraper with:

> pip3 install vk-scraper --upgrade

Thanks

**Comment by rsxrwscjpzdzwpxaujrr** [comment]
@DrLightman Hi. This command should work for you:
```
pip3 install --force git+https://github.com/rsxrwscjpzdzwpxaujrr/VK-Scraper
```

**Comment by DrLightman** [comment]
Perfect, it works like a charm! Thank you for you fixes.

Now I I try to make an exe out of it :)

**Comment by vanyasem** [comment]
Thank you for the PR! I'll review it soon and upload to PyPi

**Comment by vanyasem** [comment]
Looks good to me, I'll merge it and make a few adjustments afterwards myself. Thank you for the contribution. Sorry for the late review, I've been in the process of moving from one country to another.

**Review by vanyasem — APPROVED** [review]

**Pull request merged**
